"""
Django settings for realestate project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-pk2xg)%6+0h#^i__cy@1su#n*y0*k$i--!52yn!1xgfr=-33^v',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'anymail',
    'listings',
    'pages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'realestate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'realestate.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'realestate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# Change this to switch the currency symbol shown across the site (e.g. '₹', '£', '€')
CURRENCY_SYMBOL = os.environ.get('CURRENCY_SYMBOL', '$')

# Company / site info — shown in the navbar, footer, contact page and outgoing emails.
# Change these in .env instead of editing templates directly.
COMPANY_NAME = os.environ.get('COMPANY_NAME','Indus-Reality')
COMPANY_TAGLINE = os.environ.get('COMPANY_TAGLINE', "Let's talk about your property plans")
COMPANY_ADDRESS = os.environ.get('COMPANY_ADDRESS', '123 Main Street, Your City')
COMPANY_PHONE = os.environ.get('COMPANY_PHONE', '(555) 123-4567')
COMPANY_WHATSAPP = os.environ.get('COMPANY_WHATSAPP', COMPANY_PHONE)
COMPANY_EMAIL = os.environ.get('COMPANY_EMAIL', 'info@indusreality.example')
COMPANY_WEBSITE = os.environ.get('COMPANY_WEBSITE', '')

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploaded property images)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# https://anymail.dev/en/stable/esps/amazon_ses/
#
# Set EMAIL_PROVIDER in .env to choose how contact form emails are sent:
#   EMAIL_PROVIDER=ses    -> Amazon SES via django-anymail (needs AWS_* vars below)
#   EMAIL_PROVIDER=smtp   -> plain SMTP (needs EMAIL_HOST etc. below)
#   (unset)               -> prints emails to the console (dev default, no setup)
#
# Amazon SES (.env):
#   EMAIL_PROVIDER=ses
#   AWS_ACCESS_KEY_ID=...
#   AWS_SECRET_ACCESS_KEY=...
#   AWS_SES_REGION_NAME=us-east-1
#   DEFAULT_FROM_EMAIL=noreply@yourdomain.com   (must be an SES-verified identity)
#   CONTACT_TO_EMAIL=client@example.com
#
# SMTP (.env), e.g. Gmail with an App Password:
#   EMAIL_PROVIDER=smtp
#   EMAIL_HOST=smtp.gmail.com
#   EMAIL_PORT=587
#   EMAIL_HOST_USER=you@example.com
#   EMAIL_HOST_PASSWORD=your-app-password
#   EMAIL_USE_TLS=True
#   CONTACT_TO_EMAIL=client@example.com

EMAIL_PROVIDER = os.environ.get('EMAIL_PROVIDER', '').lower()

if EMAIL_PROVIDER == 'ses':
    EMAIL_BACKEND = 'anymail.backends.amazon_ses.EmailBackend'
    ANYMAIL = {
        'AMAZON_SES_CLIENT_PARAMS': {
            'aws_access_key_id': os.environ.get('AWS_ACCESS_KEY_ID'),
            'aws_secret_access_key': os.environ.get('AWS_SECRET_ACCESS_KEY'),
            'region_name': os.environ.get('AWS_SES_REGION_NAME', 'us-east-1'),
        },
    }
    EMAIL_HOST_USER = ''
elif EMAIL_PROVIDER == 'smtp':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST_USER = ''

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@example.com')
CONTACT_TO_EMAIL = os.environ.get('CONTACT_TO_EMAIL', EMAIL_HOST_USER or 'admin@example.com')
